/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import conversion.Conversiones;
import division.Division;
import division.DivisionPlus;
import multiplicacion.Multiplicacion;
import multiplicacion.MultiplicacionPlus;
import resta.Resta;
import resta.RestaPlus;
import suma.Suma;
import suma.SumaPlus;

/**
 *
 * @author Daniel Andrade
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Calculadora de Bases Numericas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sumaMismaBaseBut = new javax.swing.JButton();
        multMismaBaseBut = new javax.swing.JButton();
        restaMismaBaseBut = new javax.swing.JButton();
        divMismaBaseBut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        sumaDifBaseBut = new javax.swing.JButton();
        multDifBaseBut = new javax.swing.JButton();
        restaDifBaseBut = new javax.swing.JButton();
        divDifBaseBut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        conversionesBut = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        salirBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 7, 7));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de Bases Numericas");

        jPanel2.setBackground(new java.awt.Color(20, 20, 20));

        sumaMismaBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        sumaMismaBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        sumaMismaBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        sumaMismaBaseBut.setText("Sumar");
        sumaMismaBaseBut.setBorder(null);
        sumaMismaBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaMismaBaseButActionPerformed(evt);
            }
        });

        multMismaBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        multMismaBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        multMismaBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        multMismaBaseBut.setText("Multiplicar");
        multMismaBaseBut.setBorder(null);
        multMismaBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multMismaBaseButActionPerformed(evt);
            }
        });

        restaMismaBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        restaMismaBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        restaMismaBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        restaMismaBaseBut.setText("Restar");
        restaMismaBaseBut.setBorder(null);
        restaMismaBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaMismaBaseButActionPerformed(evt);
            }
        });

        divMismaBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        divMismaBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        divMismaBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        divMismaBaseBut.setText("Dividir");
        divMismaBaseBut.setBorder(null);
        divMismaBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divMismaBaseButActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Misma Base");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(restaMismaBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(divMismaBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sumaMismaBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multMismaBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multMismaBaseBut)
                    .addComponent(sumaMismaBaseBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaMismaBaseBut)
                    .addComponent(divMismaBaseBut))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(20, 20, 20));

        sumaDifBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        sumaDifBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        sumaDifBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        sumaDifBaseBut.setText("Sumar");
        sumaDifBaseBut.setBorder(null);
        sumaDifBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaDifBaseButActionPerformed(evt);
            }
        });

        multDifBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        multDifBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        multDifBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        multDifBaseBut.setText("Multiplicar");
        multDifBaseBut.setBorder(null);
        multDifBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multDifBaseButActionPerformed(evt);
            }
        });

        restaDifBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        restaDifBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        restaDifBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        restaDifBaseBut.setText("Restar");
        restaDifBaseBut.setBorder(null);
        restaDifBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaDifBaseButActionPerformed(evt);
            }
        });

        divDifBaseBut.setBackground(new java.awt.Color(41, 41, 41));
        divDifBaseBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        divDifBaseBut.setForeground(new java.awt.Color(255, 255, 255));
        divDifBaseBut.setText("Dividir");
        divDifBaseBut.setBorder(null);
        divDifBaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divDifBaseButActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Diferente Base");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(sumaDifBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(multDifBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(restaDifBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divDifBaseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multDifBaseBut)
                    .addComponent(sumaDifBaseBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaDifBaseBut)
                    .addComponent(divDifBaseBut))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(20, 20, 20));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        conversionesBut.setBackground(new java.awt.Color(41, 41, 41));
        conversionesBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        conversionesBut.setForeground(new java.awt.Color(255, 255, 255));
        conversionesBut.setText("Converciones");
        conversionesBut.setBorder(null);
        conversionesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionesButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(conversionesBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversionesBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel9.setBackground(new java.awt.Color(20, 20, 20));

        salirBut.setBackground(new java.awt.Color(41, 41, 41));
        salirBut.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        salirBut.setForeground(new java.awt.Color(255, 255, 255));
        salirBut.setText("Salir");
        salirBut.setBorder(null);
        salirBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salirBut, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salirBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multMismaBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multMismaBaseButActionPerformed
        Multiplicacion mult = new Multiplicacion();
        mult.setVisible(true);
    }//GEN-LAST:event_multMismaBaseButActionPerformed

    private void restaMismaBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaMismaBaseButActionPerformed
        Resta resta = new Resta();
        resta.setVisible(true);
    }//GEN-LAST:event_restaMismaBaseButActionPerformed

    private void divMismaBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divMismaBaseButActionPerformed
        Division div = new Division();
        div.setVisible(true);
    }//GEN-LAST:event_divMismaBaseButActionPerformed

    private void multDifBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multDifBaseButActionPerformed
        MultiplicacionPlus multp = new MultiplicacionPlus();
        multp.setVisible(true);
    }//GEN-LAST:event_multDifBaseButActionPerformed

    private void restaDifBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaDifBaseButActionPerformed
        RestaPlus restap = new RestaPlus();
        restap.setVisible(true);
    }//GEN-LAST:event_restaDifBaseButActionPerformed

    private void divDifBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divDifBaseButActionPerformed
        DivisionPlus divp = new DivisionPlus();
        divp.setVisible(true);
    }//GEN-LAST:event_divDifBaseButActionPerformed

    private void salirButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButActionPerformed
        salir();
    }//GEN-LAST:event_salirButActionPerformed

    private void sumaMismaBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaMismaBaseButActionPerformed
        Suma suma = new Suma();
        suma.setVisible(true);
    }//GEN-LAST:event_sumaMismaBaseButActionPerformed

    private void sumaDifBaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaDifBaseButActionPerformed
        SumaPlus sumap = new SumaPlus();
        sumap.setVisible(true);
    }//GEN-LAST:event_sumaDifBaseButActionPerformed

    private void conversionesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionesButActionPerformed
        Conversiones conv = new Conversiones();
        conv.setVisible(true);
    }//GEN-LAST:event_conversionesButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conversionesBut;
    private javax.swing.JButton divDifBaseBut;
    private javax.swing.JButton divMismaBaseBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton multDifBaseBut;
    private javax.swing.JButton multMismaBaseBut;
    private javax.swing.JButton restaDifBaseBut;
    private javax.swing.JButton restaMismaBaseBut;
    private javax.swing.JButton salirBut;
    private javax.swing.JButton sumaDifBaseBut;
    private javax.swing.JButton sumaMismaBaseBut;
    // End of variables declaration//GEN-END:variables
      private void salir(){
          System.exit(0);
      }
}
